services:
  - type: web
    name: tiffin-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    pythonVersion: 3.11.9
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.ayekeqjyfelqlarclfod:Tiffin#12D*@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: SECRET_KEY
        value: secrecy-at-its-peak
