services:
  - type: web
    name: tiffin-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MYSQL_HOST
        value: your-remote-mysql-host
      - key: MYSQL_USER
        value: your-mysql-username
      - key: MYSQL_PASSWORD
        value: your-mysql-password
      - key: MYSQL_DB
        value: swadisht
      - key: SECRET_KEY
        value: your-secret-key
